name: flx_authentication_flutter
version: 0.0.1
environment:
  sdk: ">=3.4.0 <4.0.0"
  flutter: ">=1.17.0"
description: A lightweight Flutter package for email & password sign-in.
homepage: https://github.com/flexurio/flx_authentication_flutter
repository: https://github.com/flexurio/flx_authentication_flutter
issue_tracker: https://github.com/flexurio/flx_authentication_flutter/issues
dependencies:
  dio: ^5.8.0+1
#  flx_core_flutter:
#    git:
#      url: https://gitlab.com/VNEU/flexurio-erp-core.git
#      ref: main
  flx_core_flutter:
    path: ../flx_core_flutter
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.0
  freezed_annotation: ^2.2.0
  go_router: ^14.3.0
  gap: ^3.0.1
  pinput: ^2.2.31
  hive: ^2.2.3
  hydrated_bloc: ^10.0.0
  pattern_formatter: ^4.0.0
  screen_identifier: ^0.0.2
dev_dependencies:
  build_runner: ^2.4.6
  build_runner_core: ^7.2.9
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.0
  json_serializable: ^6.5.4
  pubspec_dependency_sorter: ^1.0.5
  very_good_analysis: ^5.1.0
dependency_overrides:
  intl: ^0.20.2
flutter: null
